### ISSUE TITLE
cant install the requirements.

### ISSUE THREAD

**Issue by mursalatul** [TamimulAhsan/contact_management#1]
When I am trying to install the requirements to run the program, it is saying 

- **Could not find a version that satisfies the requirement csv (from versions: none).** 
- **No matching distribution found for csv.**

![image](https://user-images.githubusercontent.com/79168756/225405280-8ecbf2aa-0287-4e16-b0ee-e9fbb97b7556.png)

**Comment by TamimulAhsan** [comment]
Hey, My mistake. Please remove csv form the requirements.txt file. Or redownload the requirements file I have updated it.
CSV is a standard module. You don't need to install it. I mistakently added it.
Thanks for pointing it out

**Comment by mursalatul** [comment]
thanks for the quick response.

**Comment by mursalatul** [comment]
cant find the msvcrt module while running the management.py 
![image](https://user-images.githubusercontent.com/79168756/225451749-08c9efe3-b8c8-46ab-b532-1a597d03bc94.png)

**Comment by TamimulAhsan** [comment]
What's your OS? If you're trying to run it on Linux/Mac it won't work. Msvcrt is a windows dll file. (Read the new Readme.md file)

I'll fix it soon.

**Comment by mursalatul** [comment]
I got it now. I use Linux. 
Thanks for the response.

**Comment by TamimulAhsan** [comment]
> I got it now. I use Linux. Thanks for the response.

Hey, I have made changes to the code. You should be able to run it on linux/Mac now. Try it out.
